# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: release-drafter
        uses: release-drafter/release-drafter@v5
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.ASSETS_TOKEN }}

      - name: last-release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ASSETS_TOKEN }}
        with:
          release_id: ${{ steps.release.outputs.id }}

      # Runs a single command using the runners shell
      - name: install
        run: npm install

      # Runs a set of commands using the runners shell
      - name: build-production
        run: npm run build:production
        env:
          GH_TOKEN: ${{ secrets.ASSETS_TOKEN }}

      - name: release-upload
        uses: chaosddp/upload_asset_to_release@v0.1
        with:
          repo: moni-mua-stream
          owner: yousalice
          tag_name: ${{ steps.release.outputs.tag_name }}
          token: ${{ secrets.ASSETS_TOKEN }}
          asset: "build/*.{zip,exe}"
